---
version: '3'

services:
  zclassicd:
    build: .
    env_file:
      - .env
    volumes:
      - ./zcash-params-dir:/srv/zclassicd/.zcash-params
      - ./zcash-data-dir:/srv/zclassicd/.zclassic
